check50:
  files: &check50_files
    - !exclude "*"
    - !require caesar.c

submit50:
  files: *check50_files
  remote:
    message: "Go to your dashboard at https://cs50.cs.yale.edu/20su/dashboard to see your score and access your check50 and style50 output.  (It may take a few minutes for this submission to appear.)"
    callback: https://cs50.cs.yale.edu/20su/api/submit50
