check50: 
  files: &check50_files
    - !exclude "*"
    - !require index.html
    - !include "*.css"
    - !include "*.html"
    - !include "*.js"
    - !include "*.md"
    - !include "*.txt"

submit50:
  files: *check50_files
  style: false