submit50:
  files: &submit50_files
    - !exclude "__pycache__"
    - !exclude "node_modules"
    - !exclude "venv"
    - !require DESCRIPTION
    - !require NAMESPACE
    - !require R/
    - !require man/
    - !require tests/
  style: false

check50:
  files: *submit50_files